#!/usr/bin/env ruby
$from_branch
$msg

def merge?
	ARGV[1] == "merge"
end

def merge_msg
  $msg ||= `cat .git/MERGE_MSG`
  $from_branch = $msg[14..15]
end

merge_msg

if merge? #&& from_ws
  puts "STOP THE MERGE!"
  puts "Merge from - #$from_branch"
  puts "Never merge from WS branch! Thanks"
  exit 1
end