#!/usr/bin/env ruby
$from_branch
$msg
$branch

def merge?
	ARGV[1] == "merge"
end

def merge_msg
  $msg ||= `cat .git/MERGE_MSG`
  $msg[13..16]
end

$branch = merge_msg

if merge?
  puts "STOP THE MERGE!"
  puts "#$msg"
  puts "Never merge from WS branch! Thanks"
  exit 1
end